docker/registry/certs/generator/generate.sh

Make sure the regex only matches IPs, not nip.io domain names.
Use correct name for secret.

Fix docker/registry/certs/generator/generate.sh

---

scf/README.md
scf/helm/cf/templates/bits.yaml
scf/helm/cf/templates/eirini.yaml
scf/helm/cf/values.yaml

Hey guys,
This is the helm template we currently use to deploy Bits-Service and use it as OCI image registry. I think we'll need a couple of iterations before this can be merged. E.g. We had to change the `external_eirini_address` to use `.Values.kube.external_ips` instead of the ingress endpoint. Maybe we can figure out a way to avoid this, in case that is preferable.
Curious to get your feedback.
Thanks,
Peter

Introduce Bits-Service OCI registry

---

values.yaml

The default values.yaml that we tell users to base their values.yaml off doesn't have loadbalancer variable. It is required by anybody trying to deploy on GKE.

Add loadbalancer config to sample values.yml

---

helm/eirini/templates/bits.yaml

Hey guys,
The latest version of the Bits-Service OCI registry requires a `registry_endpoint` to be set in the `bits.yaml` `configmap`.
The `registry_endpoint` is an HTTP virtual host and must match whatever is in `registry_address` in the eirini `configmap`.
Also, it removes the port on the `public_endpoint` as this is not used. The port can be specified in the `Port` property.
This change does all this.

Add registry_endpoint to bits configmap

---

helm/eirini/templates/bits.yaml

This enables us to introduce a new image that does not have an embedded eirinifs.
So far Bits-Service had the eirinifs baked into the image itself. We'll remove that in future Bits-Service docker images and download it explicitly in an init-container. To avoid breaking everyone else, and until we have made the necessary changes in helm `bits.yaml`, we'll pin the version here.

Pin bits-service image tag to 2.25.0-dev.6

---

helm/eirini/templates/bits.yaml

Add optional blobstore configuration parameter to the `values.yaml` to
override the default `webdav` blobstore configuration.
Example:
```
bits:
blobstore_config:
droplets: &droplets_config
blobstore_type: AWS
s3_config:
bucket: your-fancy-bucket-name
host: s3-endpoint
access_key_id: <access-id>
secret_access_key: <access-key>
region: us-geo
s3_debug_log_level:
buildpacks: *droplets_config
packages: *droplets_config
app_stash: *droplets_config
```
Signed-off-by: Matthias Diester <matthias.diester@de.ibm.com>
Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:
1. Please base your PR off the `develop` branch.
1. Describe the change on a conceptual level. How does it work, and why should it exist? Ideally, you contribute a …

Introduce configurable blobstore configuration

---

helm/eirini/templates/bits.yaml

2.25.0-dev.7 contains the changes made in https://github.com/cloudfoundry-incubator/bits-service/pull/20, i.e. it works with **containerd**.

Pin bits-service image tag to 2.25.0-dev.7, containerd support

---

.gitignore

When developing in src/code.cloudfoundry.org/eirini,
'go get's will install binaries and packages in the eirini-release
directory.
This commit updates the .gitignore s.t. any side effects of running go
commands are ignored.

Gitignore GOPATH side effects

---

helm/eirini/templates/bits.yaml

Helm ignores it, but if I do template and then do `kubectl apply` I can see the issue.

Remove restart policy from bits pod

---

helm/eirini/templates/job-secret-smuggler.yaml

Without this change secret-smuggler fails if backoffLimit exceeds the limit which is 6 by default.
Before the fix:
```
NAME                            READY   STATUS                  RESTARTS   AGE
...
secret-generation-1-drxqp       0/1     Completed               0          8m26s
secret-smuggler-bhl8z           0/1     CrashLoopBackOff        4          8m26s
...
```
After the fix (note the 3rd column):
```
NAME                            READY   STATUS      RESTARTS   AGE
...
secret-generation-1-rrvsr       0/1     Completed   0          24m
secret-smuggler-7l9nl           0/1     Completed   0          24m
...
```

Make smuggler wait for secrets to be generated

---

docs/gke.md

The steps listed to install CertManager v0.11.0 are missing some vital steps from the instructions listed at https://hub.helm.sh/charts/jetstack/cert-manager/v0.11.0
Specifically:
1.  The cert-manager CRDs must be installed before installing the Helm cert-manager chart
1.  cert-manager must be installed into the `--namespace cert-manager` namespace for following "Create a certificate issuer" instructions to work
Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:
1. Please base your PR off the `develop` branch.
1. Describe the change on a conceptual level. How does it work, and why should it exist? Ideally, you contribute a few words to the README, too.
1. Please provide automated tests (preferred) or instructions for …

Add missing steps CertManager instructions

---

helm/eirini/templates/rootfs-patcher.yml

This fixes #136 where the namespace is hard-coded for `scf` 
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:
1. Please base your PR off the `develop` branch.
1. Describe the change on a conceptual level. How does it work, and why should it exist? Ideally, you contribute a few words to the README, too.
1. Please provide automated tests (preferred) or instructions for manually testing your change.

[bug/136] remove hard coded scf namespace

---

helm/eirini/templates/configmap.yaml
helm/eirini/templates/deployment.yaml
helm/eirini/templates/events.yaml
helm/eirini/templates/fluentd-configmap.yaml
helm/eirini/templates/fluentd-daemonset.yaml
helm/eirini/templates/job-secret-smuggler.yaml
helm/eirini/templates/metrics.yaml
helm/eirini/templates/rootfs-patcher.yml
helm/eirini/templates/routing.yaml
helm/eirini/templates/service.yaml

When rendering the Eirini Helm chart, we should allow the templates to be rendered for a particular namespace. Most of the templates were supporting, but a few were not, so we are ensuring they all can now.
FWIW, we are using Helm 3 (and `helm template`) and needed to add this to use Helm 3:
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`
Can test by running `helm template --namespace foobar` and ensure the appropriate resources are placed into the `foobar` namespace
@acosta11 & @jspawar & @alex-slynko

Ensure all Eirini templates are namespaced

---

helm/eirini/templates/service.yaml

Remove external ip for service that is accessible internally.
No need for automated testing.
Pair w/ @alex-slynko
We need it for CF on K8s artifact.

Remove external ip from eirini svc

---

helm/eirini/templates/configmap.yaml
helm/eirini/templates/lrp-controller-pod-security-policy.yaml
helm/eirini/templates/lrp-controller.yaml
helm/eirini/templates/lrp-crd.yaml
helm/eirini/values.yaml

Note: The LRP Controller is currently disabled (`enable:false` in values.yml) so it shouldn't break anything in CI when this is merged. When we merge https://github.com/cloudfoundry-incubator/eirini/pull/97 and update our CI we can flip it to `true`.

Add the LRP CRD and the LRP Controller deployment templates

---

helm/eirini/templates/configmap.yaml

Align `MetricsCollectorConfig` `LoggregatorCertPath` yaml custom key with other properties.
Corresponding PR for [eirini PR#103](https://github.com/cloudfoundry-incubator/eirini/pull/103)

Fix custom key spelling for LoggregatorCertPath

---

helm/eirini/templates/configmap.yaml
helm/eirini/values.yaml

cloudfoundry-for-kubernetes (cf-for-k8s) is using istio so the URLs can be open and istio will handle encryption automatically
The defaults we've added maintain status quo, but it's easier to configure this URL now.
CF relint story link:
[#172615287](https://www.pivotaltracker.com/story/show/172615287)
Redo of PR #169 to deal with CLA hassles

Make the eirini<=>api URL more configurable

---

deploy/core/instance-index-env-injector.yml
helm/eirini/templates/instance-index-env-injector.yml

Use the correct svc port for env injector.
After bumping eirinix (https://github.com/cloudfoundry-incubator/eirini/commit/ea0b5ea9a70f59ab499514be038f3e5421b5cf8b)
now the Port setting on the Manager config works as expected:
https://github.com/cloudfoundry-incubator/eirini/blob/master/cmd/instance-index-env-injector/main.go#L37
thus the kube api was trying to access our webhook on a service
listening on port 8443, while our service was listening on port 443 instead.
This should fix CI errors: https://jetson.eirini.cf-app.com/teams/main/pipelines/ci/jobs/run-eats-tests-monaco/builds/41

Fix yamls after eirini bump

---

helm/eirini/templates/deployment.yaml
helm/eirini/templates/eirini-controller.yml
helm/eirini/templates/events.yaml
helm/eirini/templates/task-reporter.yaml

Cf-for-K8s is currently working on a scaling and Quality of Service (QoS) set of stories.
We are targeting 1.0 to be configured out-of-the-box as a "developer" edition aimed at those users who want to kick the tires. As part of this, we would like to set limits on mem/cpu. 
Since a "developer" edition may not be preferred by everyone, we want each component to be configurable to scale both horizontally (replicas) and vertically (mem/cpu). This will also allow users to deliver a Guaranteed QoS when required (although we are recommending that all of our pods and containers use the Burstable QoS) As part of this we would like to ask you to do several things:
1. consider which of your pods/containers you would like to expose for
scaling properties for for both horizontal (deployment replicas) …

Set memory and cpu requests and limit values for all containers

---

helm/cf/templates/pdb.yml

Operator "and" always evaluates all parameters thus the original expression fails if `count` is not defined.
The error message is `error calling gt: invalid type for comparison`.
Fixing with a nested "if".
See https://stackoverflow.com/a/59796677

cf: Do not fail when router count is not defined
