README.md

This should make it easier to use LogCache by following the instructions.

Update LogCache usage instructions

---

README.md

Inspired by https://github.com/cloudfoundry/cloud_controller_ng/blob/master/README.md#helpful-resources

Add link to pipeline

---

docker/registry/certs/copier/copy.sh
scf/README.md
scf/helm/cf/templates/eirini.yaml

The cert-copy job, that copies registry certs to the
docker deamon certs repository was turned from an job
into a daemonset.
[#161279275]
Signed-off-by: Mario Nitchev <marionitchev@gmail.com>
Signed-off-by: Julian Skupnjak <skupnjak@de.ibm.com>

Eanble multi-cluster deployments

---

scf/README.md

Signed-off-by: Steffen Uhlig <Steffen.Uhlig@de.ibm.com>

Add clarification for the opi.image_tags property

---

.github/contributing.md

There are no unit tests currently.
[fixes #164088189]

Remove obsolete section

---

helm/eirini/values.yaml

remove duplicate `image_tag` key

---

helm/eirini/templates/bits.yaml
helm/eirini/templates/configmap.yaml
helm/eirini/templates/daemonset.yaml
helm/eirini/templates/job-create-certs.yaml
helm/eirini/values.yaml

This PR solves the merge conflicts from https://github.com/cloudfoundry-incubator/eirini-release/pull/28

Added loadbalancer support to registry

---

README.md

small update on the supported versions of platform / tools.

add supported platform versions to the doc

---

helm/eirini/templates/configmap.yaml
helm/eirini/values.yaml

Signed-off-by: Julian Skupnjak <skupnjak@de.ibm.com>
Bump Eirini and update helm values for `stager_image_tag` -> `stager_image` change.

Bump Eirini

---

README.md

Certificates

---

helm/eirini/templates/bits.yaml

Fix another .Values.env.DOMAIN bug

---

helm/eirini/templates/configmap.yaml
helm/eirini/templates/deployment.yaml
helm/eirini/values.yaml

Signed-off-by: Oleksandr Slynko <oslynko@pivotal.io>

Split staging image into three

---

README.md
helm/eirini/templates/networkpolicy.yml

Set up a network policy to deny access between apps

---

README.md

Add notes on securing K8s API using Network Policy

---

README.md

Document troubleshooting disk full on blobstore

---

helm/eirini/templates/rootfs-patcher-service-account.yaml

[#168072074]
Only merge it when https://github.com/cloudfoundry-incubator/eirini/pull/73 is merged

Change bits-waiter role to allow get on deployment

---

helm/eirini/Chart.yaml

Thanks for contributing to Eirini! In order for your pull request to be accepted, we would like to ask you the following:
[x] Please base your PR off the `develop` branch.
> [ ] Describe the change on a conceptual level. How does it work, and why should it exist? Ideally, you contribute a few words to the README, too.
> [ ] Please provide automated tests (preferred) or instructions for manually testing your change.
Trivial spelling fix only.

Fix spelling of Cloud Foundry

---

README.md

1.0 docs fixes

---

helm/eirini/values.yaml

Remove unused variable

---

deploy/events/event-reporter-configmap.yml
deploy/events/event-reporter-deployment.yaml
deploy/events/event-reporter-rbac.yml
helm/eirini/templates/events.yaml

[Link](https://www.pivotaltracker.com/story/show/174377714) to story.
Related to https://github.com/cloudfoundry-incubator/eirini/pull/111

Add plain event reporter templates
